#!/bin/bash
for FILE in /usr/local/Warehouse/stock/*; 
do
	source $FILE
done

for FILE in /usr/local/Warehouse/refurbish/*;
do
	source $FILE
done

for FILE in /usr/local/Warehouse/return/*;
do
	source $FILE
done

if [ "$1" == "order" ];
then
	if [ "$2" == "a52dec" ];
	then
		a52dec_install

	elif [ "$2" == "aalib" ];
	then
		aalib_install
	elif [ "$2" == "aardvark_shell_utils" ];
	then
		aardvark_install
	else
		echo -e "\033[91;1;4mError: Product not in stock \033[0m"
		echo "Try refurbishing (maintaining, updating) VirtualShip."
	fi
		
elif [ "$1" == "refurbish" ];
then
	if [ "$2" == "ship" ];
	then
		maintain
		rm -rf /usr/local/Warehouse/maintain.sh
		rm -rf /usr/local/Warehouse/requirements.txt
		rm -rf /usr/local/Warehouse/return.sh
		rm -rf /usr/local/Warehouse/refurbish.sh
	elif [ "$2" == "a52dec" ];
	then
		a52dec_update
	elif [ "$2" == "aalib" ];
	then
		aalib_update
	elif [ "$2" == "aardvark_shell_utils" ];
	then
		aardvark_update
	else
		echo -e "\033[91;1;4mError: Product not in stock \033[0m"
		fi
elif [ "$1" == "return" ];
then
	if [ "$2" == "a52dec" ];
	then
		un_a52dec
	elif [ "$2" == "aalib" ];
	then
		un_aalib
	elif [ "$2" == "aardvark_shell_utils" ];
	then
		un_aardvark
	else
		echo "Error: product not in stock"
	fi
else
	echo -e "\033[91;1;4mError: Command not understood \033[0m"
	fi
