#!/bin/bash
source /usr/local/Warehouse/stock/a52dec_install.sh
source /usr/local/Warehouse/stock/aalib_install.sh
source /usr/local/Warehouse/maintain.sh
source /usr/local/Warehouse/refurbish.sh
source /usr/local/Warehouse/return.sh
if [ "$1" == "order" ];
then
	if [ "$2" == "a52dec" ];
	then
		a52dec_install

	elif [ "$2" == "aalib" ];
	then
		aalib_install
	else
		echo -e "\033[91;1;4mError: Product not in stock \033[0m"
		echo "Try refurbishing (maintaining, updating) VirtualShip."
	fi
		
elif [ "$1" == "refurbish" ];
then
	if [ "$2" == "ship" ];
	then
		maintain
	elif [ "$2" == "a52dec" ];
	then
		a52dec_update
	elif [ "$2" == "aalib" ];
	then
		aalib_update
	else
		echo -e "\033[91;1;4mError: Product not in stock \033[0m"
		fi
elif [ "$1" == "return" ];
then
	if [ "$2" == "a52dec" ];
	then
		un_a52dec
	elif [ "$2" == "aalib" ];
	then
		un_aalib
	else
		echo "Error: product not in stock"
	fi
else
	echo -e "\033[91;1;4mError: Command not understood \033[0m"
	fi
