.TH "GDRIVED" "1" "January 2021" "VirtualShip" "gdrived"
.
.SH "NAME"
\fBship\fR \- The auxiliary ship command for downloading files from Google Drive, using curl.
.
.SH "SYNOPSIS"
\fBsha\fR [\fIID\fR]
.
.SH "DESCRIPTION"
The VirtualShip project uses Google Drive as its main secure source for storing archived files available for the ship command to use.
The gdrived helps the ship command by using curl to download files. Gdrived also eliminates the need for a dependency, gdown.
.
.SH "ID"
.
The ID is part of a Google Drive link.
.
.SH "BUGS"
See our issues on GitHub:
.
.TP
\fBVirtualShip/Core\fR
.
.br
\fIhttps://github\.com/VirtualShip/Core/issues\fR
